"""Type stubs for the native `_rust_accel` PyO3 extension module (see rust/src/lib.rs)."""

import numpy as np
from numpy.typing import NDArray

__version__: str
__doc__: str

def apply_sauvola_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_geo_warp_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_vertical_crop_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_blur_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_salt_pepper_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_background_texture_rust(
    img: NDArray[np.uint8], intensity: float
) -> NDArray[np.uint8]: ...
def apply_jpeg_compression_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_rotation_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_lowdpi_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_oversample_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_perspective_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_elastic_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_random_crop_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_online_blur_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_online_noise_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_reverse_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_brightness_contrast_rust(
    img: NDArray[np.uint8], intensity: float
) -> NDArray[np.uint8]: ...
def apply_pixelation_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_gradient_illumination_rust(
    img: NDArray[np.uint8], intensity: float
) -> NDArray[np.uint8]: ...
def apply_morphological_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_anisotropic_dilation_rust(
    img: NDArray[np.uint8], intensity: float
) -> NDArray[np.uint8]: ...
def apply_hsv_rgb_rust(img: NDArray[np.uint8], intensity: float) -> NDArray[np.uint8]: ...
def apply_brightness_contrast_rgb_rust(
    img: NDArray[np.uint8], intensity: float
) -> NDArray[np.uint8]: ...
def aug_methods_dict() -> dict[str, object]: ...

class RustFontManager:
    def __init__(self) -> None: ...
    def load(self, fonts_dir: str) -> None: ...
    def glyph_supported(self, font_path: str, ch: str) -> bool: ...
    def text_supported(self, font_path: str, text: str) -> bool: ...
    def text_has_khmer(self, text: str) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class FontFace:
    @staticmethod
    def from_file(path: str) -> FontFace: ...
    def glyph_exists(self, c: str) -> bool: ...
    def text_supported(self, text: str) -> bool: ...
    def __repr__(self) -> str: ...

def split_text_spans(text: str) -> list[tuple[str, str]]: ...
def estimate_bg_rust(img: NDArray[np.uint8]) -> int: ...
def image_is_blank_rust(img: NDArray[np.uint8], threshold: int, min_ratio: float) -> bool: ...
def write_image_rust(img: NDArray[np.uint8], path: str, format: str, quality: int) -> bool: ...
